{{- range .Values.kafka.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.kafka.cluster }}
    {{- include "kafka-topics.labels" $ | nindent 4 }}    
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
    retention.ms: {{ .retention }}
    segment.bytes: 1073741824
{{- end }} 
