apiVersion: v2
name: globex
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
  - name: retail-db
    version: 0.1.0
    repository: file://retail-db
  - name: kafka-broker
    version: 0.1.0
    repository: file://kafka-broker
  - name: kafka-connect
    version: 0.1.0
    repository: file://kafka-connect
  - name: kafka-topics
    version: 0.1.0
    repository: file://kafka-topics
  - name: debezium
    version: 0.1.0
    repository: file://debezium
    condition: debezium.enabled
  - name: kafdrop
    version: 0.1.0
    repository: file://kafdrop
  - name: cashback-db
    version: 0.1.0
    repository: file://cashback-db
  - name: elasticsearch
    version: 0.1.0
    repository: file://elasticsearch
    condition: elasticsearch.enabled
  - name: sales-streams
    version: 0.1.0
    repository: file://sales-streams
  - name: cashback-connector
    version: 0.1.0
    repository: file://cashback-connector
  - name: cashback-service
    version: 0.1.0
    repository: file://cashback-service
  - name: cashback-service-ui
    version: 0.1.0
    repository: file://cashback-service-ui
  - name: elastic-connector
    version: 0.1.0
    repository: file://elastic-connector
    condition: elasticsearch.enabled
  - name: search-service
    version: 0.1.0
    repository: file://search-service
    condition: elasticsearch.enabled
  - name: retail-simulation
    version: 0.1.0
    repository: file://retail-simulation
